# Generated by Django 5.0.6 on 2024-06-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_duration',
            field=models.CharField(max_length=255),
        ),
    ]
